services:
  chatbot:
    build: .
    container_name: smartblin-chatbot
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp=unconfined
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
